Feature/add limit support
apostrophecms/form pull request #34
Opened 2023-10-05 08:17 UTC by haroun

## Summary

* Add multiple option to file field
* Add file max size to file field

## What are the specific steps to test this change?

1. Create a form and add 2 file fields
2. Set the `multiple` option to false in the file field widget editor modal
3. Set the file max size option in the file field widget editor modal
4. In preview mode, try to fill the form with multiple files and files bigger than the limit set

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [ ] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [x] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2023-10-05 13:10 UTC, myovchev approved these changes

2023-10-05 13:10 UTC, myovchev commented on i18n/en.json
> +  "fileMaxSize": "Max file attachment size",
Probably "total file size" is more precise.

2023-10-06 14:02 UTC, boutell requested changes

2023-10-06 14:02 UTC, boutell commented on modules/@apostrophecms/form-file-field-widget/index.js
> +      maxSize: {
* Please put `maxSize` behind a `limitSize` boolean that hides it unless chosen using `if`, so it is clear that less technical form creators don't have to touch this, and check for `limitSize` being truthy before enforcing.

2023-10-06 14:13 UTC, boutell reviewed
In addition: looks like I was wrong that you can't have a change handler to check this right away.

Form fields are widgets and widgets can have players, therefore you can have a change handler.

See:

https://github.com/apostrophecms/form/blob/main/modules/%40apostrophecms/form-radio-field-widget/ui/src/index.js

For an example.

But if it is too messy to hook it up to error display it could be something we don't do right now.

I was also wrong about server side size enforcement, sorry!

It turns out that the entire upload is handled by the `submitForm` method in `lib/process.js`. So it is possible.

Currently though attachment uploads are processed in that method before the sanitization of fields, so it could be a bit tedious and I don't think it's a requirement that it happen in this release.

2023-10-09 14:24 UTC, boutell approved these changes

2023-10-09 14:43 UTC, merged