add icons and update packages
apostrophecms/form pull request #36
Opened 2023-10-05 10:45 UTC by haroun

## Summary

Update dependencies and fix lint issues

## What are the specific steps to test this change?

1. npm test should be green

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [ ] New feature
- [x] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [ ] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2023-10-05 10:46 UTC, haroun commented on modules/@apostrophecms/form-boolean-field-widget/index.js
> +    label: 'aposForm:boolean',
The icons do not show up. Can't figure why yet.

2023-10-05 10:47 UTC, haroun commented on modules/@apostrophecms/form-select-field-widget/index.js
> +    icon: 'form-select-icon'
this one is already defined by the form module itself

2023-10-06 13:50 UTC, boutell requested changes

2023-10-09 14:25 UTC, boutell approved these changes

2023-10-09 14:43 UTC, merged